# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelibrary',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
